### ISSUE TITLE
No access to the similarity_search_by_vector function

### ISSUE THREAD

**Issue by xindexer** [langchain-ai/langchain-weaviate#131]
There's no way to call for a near_vector search function (similarity_search_by_vector_function). One of the earlier versions had a "by_text" boolean that was used to switch to a vector search. If that is put back in then you can access it again.

`        if self._by_text:
            return self._perform_search(query, k, **kwargs)
        else:
            if self._embedding is None:
                raise ValueError(
                    "_embedding cannot be None for similarity_search when "
                    "_by_text=False"
                )
            embedding = self._embedding.embed_query(query)
            return self.similarity_search_by_vector(embedding, k, **kwargs)`

Not the best solution in my opinion, but it is working

**Comment by hkhairy** [comment]
You can, by passing a keyword argument to the search method. It's not as straightforward as it used to be, because now it relies on a hidden keyword argument called `search_method`

So, if you call
```
weaviate_vstore.similarity_search(..., search_method = "near_vector")
```
It will call the `near_vector` in the `_perform_search` method. If you open the `_perform_search` method in the source code, you'll find this
```python
if search_method == "hybrid":
    embedding = self._embedding.embed_query(query)
    result = collection.query.hybrid(
        query=query, vector=embedding, limit=k, **kwargs
    )
elif search_method == "near_vector":
    result = collection.query.near_vector(limit=k, **kwargs)
```
There's another problem though, in this block specifically
```python
elif search_method == "near_vector":
  result = collection.query.near_vector(limit=k, **kwargs)
```
The embedding of the query isn't being passed. I've raised an issue and made a PR for that. 
* #132
* #133

**Comment by xindexer** [comment]
Ok - I had tried to use the search_method but like you said it didn't pass the vector - I like your solution much better.

**Comment by hsm207** [comment]
@xindexer in this new integration, calling `similarity_search` is the way to do any search. This method calls weaviate's hybrid search under the hood. So, if you want to do vector search only, then either of the following will work:

```python
weaviate_vector_store._perform_search(query="hello", k=5)

weaviate_vector_store._perform_search(query=None, vector=[1, 2, 3], k=5)
```

**Comment by hkhairy** [comment]
@hsm207 
I think the first example will do hybrid search as well. Maybe you forgot the set the `alpha` keyword argument?

**Comment by hkhairy** [comment]
@xindexer 
In case you don't know, hybrid search is a hybrid of 2 things:
* text search (using an algorithm called BM25, or Best Match 25), 
* and vector search.

The hybrid search favors one search outcome over the other via a parameter called `alpha`. So, if `alpha` is `0.3`, then the vector search will have a weight of `0.3`, while the text search will have a weight of `0.7`. 

You can even control the weight on the level of the property. See [here](https://weaviate.io/developers/weaviate/search/hybrid) in the weaviate Docs

That's why, you'll find in @hsm207 answer, he provides the `alpha = 1` in the first example.
