### ISSUE TITLE
Document semantic caching example

### ISSUE THREAD

**Issue by shashankram** [langchain-ai/langchain-weaviate#203]
After going through several docs pertaining to Weaviate that have not helped, I would request the project to document an end-to-end example of leveraging Weaviate for semantic caching. 

The document should cover the following:
1. Setting up Weaviate locally
2. Creating a client
3. Adding key and corresponding objects into Weaviate
4. Performing lookups on semantically similar keys
5. Updating the key with a new object
6. Clearing the entries for the index

**Comment by hsm207** [comment]
Thanks for your feedback.

Documentation on langchain-weaviate in the langchain docs  is scarce because it only documents weaviate-specific features e.g. hybrid search, multi-tenancy. Since it implements the Vector Store interface, langchain's docs on that will apply to this implementation as well.

We maintain a few end-to-end examples in this repo:

https://github.com/weaviate/recipes/tree/main/integrations/llm-frameworks/langchain

Please have a look at the sample notebooks there to see if it helps and  raise an issue there to share feedback.

**Comment by shashankram** [comment]
Could you share examples on the points listed in the issue description?
